#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: the accounts and keys of the QR mechanism (spec #43, ticket #44).
# ──────────────────────────────────────────────────────────────────────────
#
# Each section runs on its own and names the ticket it unblocks:
#
#   pnpm setup:qr          shows the sections and asks which to run
#   pnpm setup:qr a b      runs sections a and b only
#
# Keys go into the Website's Vercel variables (Production and Preview, stored
# as sensitive) and into Trigger.dev's prod environment. The wizard also keeps
# each value in a local file outside git, so a re-run offers the saved values.
# It never prints a secret.

umask 077
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${QR_SETUP_ENV_FILE:-$HOME/.config/setebaid/qr-mechanism.env}"
mkdir -p "$(dirname "$ENV_FILE")"

VERCEL_TEAM="studio-rovst"
VERCEL_PROJECT="setebaid-2026"
TRIGGER_API="https://api.trigger.dev/api/v1"
FORMSPARK_API="https://api.formspark.io/public/v1"
SANITY_HOOK_NAME="Rebuild the Website when a redirect changes"

# The values the Trigger.dev tasks read. Section d copies every saved one, so
# a section that runs before d loses nothing.
TRIGGER_VARIABLES=(FORMSPARK_FORM_ID FORMSPARK_API_TOKEN DATABASE_URL FORM_ENCRYPTION_KEY
  VERCEL_ANALYTICS_TOKEN VERCEL_PROJECT_ID VERCEL_TEAM_ID RESEND_API_KEY REPORT_EMAIL_TO)

ok()   { printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$1"; }
fail() { printf '  %s✗ %s%s\n' "$RED" "$1" "$RESET"; SKIPPED+=("$1"); }

# saved KEY prints the value saved in ENV_FILE, or nothing.
saved() { _existing "$1" || true; }

# check "label" COMMAND... runs one closing check of a section.
check() {
  local label="$1"; shift
  if "$@"; then ok "$label"; else fail "Check failed: $label"; fi
}

# require TOOL... warns about each missing tool and fails if one is missing.
require() {
  local tool missing=0
  for tool in "$@"; do
    command -v "$tool" >/dev/null 2>&1 || { warn "Missing tool: $tool"; missing=1; }
  done
  return "$missing"
}

# ask_value KEY "Prompt" [secret] asks until the trimmed answer is not empty.
ask_value() {
  local value
  while :; do
    if [[ "${3:-}" == secret ]]; then ask_secret "$1" "$2"; else ask "$1" "$2"; fi
    value="${!1}"
    value="${value#"${value%%[![:space:]]*}"}"
    value="${value%"${value##*[![:space:]]}"}"
    printf -v "$1" '%s' "$value"
    [[ -n "$value" ]] && return 0
    warn "A value is required."
  done
}

# http_call TOKEN METHOD URL [JSON_BODY] calls an API with a bearer token. It
# sets HTTP_STATUS (0 when the request did not complete) and HTTP_BODY. The
# token and body travel as environment variables, not command arguments.
# Never print HTTP_BODY: it can hold secrets.
http_call() {
  local out
  out=$(TOKEN="$1" METHOD="$2" TARGET="$3" BODY="${4:-}" node --input-type=module -e '
    const { TOKEN, METHOD, TARGET, BODY } = process.env;
    const headers = { Authorization: `Bearer ${TOKEN}` };
    if (BODY) headers["Content-Type"] = "application/json";
    try {
      const response = await fetch(TARGET, { method: METHOD, headers, body: BODY || undefined });
      process.stdout.write(`${response.status}\n${await response.text()}`);
    } catch {
      process.stdout.write("0\n");
    }
  ')
  HTTP_STATUS="${out%%$'\n'*}"
  if [[ "$out" == *$'\n'* ]]; then HTTP_BODY="${out#*$'\n'}"; else HTTP_BODY=""; fi
}

# vercel_api ENDPOINT [OPTION...] calls the Vercel API as the logged-in CLI
# user, in the team that owns the Website. The response goes to stdout.
vercel_api() { vercel api "$1" --scope "$VERCEL_TEAM" --raw "${@:2}"; }

# vercel_set NAME VALUE stores a sensitive Website variable for Production and
# Preview. It replaces an older value.
vercel_set() {
  local body
  body=$(NAME="$1" VALUE="$2" jq -nc \
    '{key: env.NAME, value: env.VALUE, type: "sensitive", target: ["production", "preview"]}')
  if printf '%s' "$body" | vercel_api "/v10/projects/$VERCEL_PROJECT/env?upsert=true" -X POST --input - >/dev/null; then
    ok "set Vercel variable $1 (Production, Preview)"
  else
    fail "Vercel variable $1 is not set. Re-run this section."
  fi
}

# vercel_has NAME succeeds when the Website has NAME for Production and Preview.
vercel_has() {
  vercel_api "/v9/projects/$VERCEL_PROJECT/env" 2>/dev/null | NAME="$1" jq -e '
    [.envs[] | select(.key == env.NAME) | .target | if type == "array" then .[] else . end] as $t
    | ($t | index("production")) != null and ($t | index("preview")) != null' >/dev/null
}

trigger_ready() { [[ -n "$(saved TRIGGER_PROJECT_REF)" && -n "$(saved TRIGGER_VARIABLES_KEY)" ]]; }

# trigger_set NAME VALUE stores a variable in Trigger.dev's prod environment.
# Before section d has run, it leaves the saved value for section d to copy.
trigger_set() {
  if ! trigger_ready; then
    note "Trigger.dev is not set up yet. Section d copies $1 there."
    return 0
  fi
  local body
  body=$(NAME="$1" VALUE="$2" jq -nc '{variables: {(env.NAME): env.VALUE}, override: true}')
  http_call "$(saved TRIGGER_VARIABLES_KEY)" POST \
    "$TRIGGER_API/projects/$(saved TRIGGER_PROJECT_REF)/envvars/prod/import" "$body"
  if [[ "$HTTP_STATUS" == 200 ]]; then
    ok "set Trigger.dev variable $1 (prod)"
  else
    fail "Trigger.dev variable $1 is not set (HTTP $HTTP_STATUS). Re-run this section."
  fi
}

# trigger_has NAME VALUE succeeds when Trigger.dev prod holds exactly VALUE.
trigger_has() {
  http_call "$(saved TRIGGER_VARIABLES_KEY)" GET \
    "$TRIGGER_API/projects/$(saved TRIGGER_PROJECT_REF)/envvars/prod/$1"
  [[ "$HTTP_STATUS" == 200 ]] && VALUE="$2" jq -e '.value == env.VALUE' >/dev/null <<<"$HTTP_BODY"
}

# check_trigger NAME VALUE checks Trigger.dev once section d has run.
check_trigger() {
  if trigger_ready; then check "Trigger.dev holds $1" trigger_has "$1" "$2"; fi
}

# studio_env KEY prints a value from studio/.env.local, or nothing.
studio_env() {
  local file="$REPO_ROOT/studio/.env.local" value=""
  if [[ -f "$file" ]]; then value=$(grep -E "^$1=" "$file" | tail -n1 | cut -d= -f2-) || true; fi
  value="${value%\"}"; value="${value#\"}"
  printf '%s' "$value"
}

# ── (a) Vercel Web Analytics and Plus ────────────────────────────────────

web_analytics_enabled() {
  vercel_api "/v9/projects/$VERCEL_PROJECT" 2>/dev/null \
    | jq -e '(.webAnalytics.enabledAt // 0) > (.webAnalytics.disabledAt // 0)' >/dev/null
}

section_a() {
  stage "(a) Vercel Web Analytics and Plus · unblocks #49"
  say "Turns on the cookie-free visit counter, and Plus for UTM reports."
  open_url "https://vercel.com/$VERCEL_TEAM/$VERCEL_PROJECT/analytics"
  step "On the Analytics tab, click Enable. Skip this if it is already enabled."
  pause "Press Enter when Web Analytics is enabled."
  open_url "https://vercel.com/$VERCEL_TEAM/~/settings/billing"
  step "Scroll to Add-ons. Under Web Analytics Plus, turn the switch on."
  note "Plus costs \$10 per month for the Studio ROVST team and covers all its projects."
  pause "Press Enter when Plus is on."
  printf '\n'
  check "Vercel reports Web Analytics enabled for $VERCEL_PROJECT" web_analytics_enabled
  note "Vercel has no public check for Plus, so this answer is yours:"
  if confirm "Does the Billing page show Web Analytics Plus as enabled?"; then
    ok "Web Analytics Plus is on"
  else
    fail "Turn on Web Analytics Plus: Team Settings → Billing → Add-ons"
  fi
  pause "Press Enter to continue."
}

# ── (b) Deploy hook and Sanity webhook ───────────────────────────────────

deploy_hook_known() {
  vercel_api "/v9/projects/$VERCEL_PROJECT" 2>/dev/null | HOOK_URL="$VERCEL_DEPLOY_HOOK_URL" jq -e \
    'any(.link.deployHooks[]?; .url == env.HOOK_URL and .ref == "main")' >/dev/null
}

# sanity_hooks TOKEN PROJECT lists the project's webhooks into HTTP_BODY.
sanity_hooks() { http_call "$1" GET "https://api.sanity.io/v2021-10-04/hooks/projects/$2"; }

# sanity_hook_state prints missing, same or different for the webhook list
# in HTTP_BODY.
sanity_hook_state() {
  NAME="$SANITY_HOOK_NAME" HOOK_URL="$VERCEL_DEPLOY_HOOK_URL" jq -r '
    [.[] | select(.name == env.NAME)] as $mine
    | if ($mine | length) == 0 then "missing"
      elif any($mine[]; .url == env.HOOK_URL) then "same"
      else "different" end' <<<"$HTTP_BODY"
}

# sanity_hook_ok TOKEN PROJECT DATASET: the webhook calls the deploy hook for
# published Redirect documents only.
sanity_hook_ok() {
  sanity_hooks "$1" "$2"
  [[ "$HTTP_STATUS" == 200 ]] || return 1
  NAME="$SANITY_HOOK_NAME" HOOK_URL="$VERCEL_DEPLOY_HOOK_URL" DATASET="$3" jq -e '
    any(.[]; .name == env.NAME and .url == env.HOOK_URL and .dataset == env.DATASET
      and .rule.filter == "_type == \"redirect\"" and (.includeDrafts | not) and (.isDisabled | not))' \
    <<<"$HTTP_BODY" >/dev/null
}

section_b() {
  stage "(b) Deploy hook and Sanity webhook · unblocks #48"
  say "Publishing a Redirect in the Studio will rebuild the Website."
  open_url "https://vercel.com/$VERCEL_TEAM/$VERCEL_PROJECT/settings/git"
  step "Under Deploy Hooks, enter the name 'sanity-redirects' and the branch 'main'. Click Create Hook."
  step "Copy the hook URL. Anyone with it can start a deploy, so treat it as a secret."
  ask_value VERCEL_DEPLOY_HOOK_URL "Paste the deploy hook URL:" secret
  write_env VERCEL_DEPLOY_HOOK_URL "$VERCEL_DEPLOY_HOOK_URL"

  local token project dataset state
  token=$(studio_env SANITY_AUTH_TOKEN)
  project=$(studio_env SANITY_STUDIO_PROJECT_ID)
  dataset=$(studio_env SANITY_STUDIO_DATASET)
  if [[ -z "$token" || -z "$project" || -z "$dataset" ]]; then
    fail "studio/.env.local needs SANITY_AUTH_TOKEN, SANITY_STUDIO_PROJECT_ID and SANITY_STUDIO_DATASET. Add them, then re-run section b."
    pause "Press Enter to continue."
    return 0
  fi

  printf '\n'
  say "Sanity webhook in project $project, dataset $dataset:"
  note "Name: $SANITY_HOOK_NAME"
  note "Trigger: create, update and delete of published documents where _type == \"redirect\""
  note "Target: the deploy hook above (POST)"
  sanity_hooks "$token" "$project"
  if [[ "$HTTP_STATUS" == 200 ]]; then state=$(sanity_hook_state); else state=error; fi
  case "$state" in
    same) ok "The Sanity webhook already exists" ;;
    different) fail "A Sanity webhook with this name calls another URL. Delete it at https://www.sanity.io/manage/project/$project/api#webhooks, then re-run section b." ;;
    error) fail "Sanity refused to list webhooks (HTTP $HTTP_STATUS). Check SANITY_AUTH_TOKEN in studio/.env.local." ;;
    missing)
      if confirm "Create this Sanity webhook now?"; then
        local body
        body=$(NAME="$SANITY_HOOK_NAME" HOOK_URL="$VERCEL_DEPLOY_HOOK_URL" DATASET="$dataset" jq -nc '{
          type: "document", name: env.NAME, url: env.HOOK_URL, dataset: env.DATASET,
          description: "Starts a Vercel deploy so that published redirects go live. Created by scripts/setup-qr-mechanism.sh.",
          apiVersion: "v2025-02-19", httpMethod: "POST", includeDrafts: false, includeAllVersions: false,
          rule: {on: ["create", "update", "delete"], filter: "_type == \"redirect\"", projection: "{_id}"}}')
        http_call "$token" POST "https://api.sanity.io/v2021-10-04/hooks/projects/$project" "$body"
        if [[ "$HTTP_STATUS" == 200 || "$HTTP_STATUS" == 201 ]]; then
          ok "created the Sanity webhook"
        else
          fail "Sanity did not create the webhook (HTTP $HTTP_STATUS). Your token may need the Administrator role."
        fi
      else
        fail "Sanity webhook not created. Re-run section b when you are ready."
      fi ;;
  esac

  printf '\n'
  check "Vercel knows the deploy hook (branch main)" deploy_hook_known
  check "The Sanity webhook calls the deploy hook for published redirects" \
    sanity_hook_ok "$token" "$project" "$dataset"
  pause "Press Enter to continue."
}

# ── (c) Formspark ────────────────────────────────────────────────────────

formspark_token_ok() {
  http_call "$FORMSPARK_API_TOKEN" GET "$FORMSPARK_API/me"
  [[ "$HTTP_STATUS" == 200 ]] && jq -e \
    '(.scopes | index("submissions:read")) != null and (.scopes | index("submissions:write")) != null' \
    <<<"$HTTP_BODY" >/dev/null
}

formspark_form_ok() {
  http_call "$FORMSPARK_API_TOKEN" GET "$FORMSPARK_API/forms/$FORMSPARK_FORM_ID/submissions?limit=1"
  [[ "$HTTP_STATUS" == 200 ]]
}

section_c() {
  stage "(c) Formspark form and API token · unblocks #50 and #52"
  say "Formspark emails each request to the office and keeps a backup copy."
  open_url "https://dashboard.formspark.io"
  step "Create a workspace named 'Setebaid', or open it. Upgrade it: a one-time payment that turns on the API."
  step "In that workspace, create a form named 'Ask about camp'. Set its notification email to the office address."
  step "Copy the form ID: the part after https://submit-form.com/ in the form's setup code."
  ask_value FORMSPARK_FORM_ID "Paste the form ID:" secret
  step "Open API tokens. Create a token named 'setebaid-jobs' with the scopes submissions:read and submissions:write. Expiry: Never."
  ask_value FORMSPARK_API_TOKEN "Paste the API token:" secret
  write_env FORMSPARK_FORM_ID "$FORMSPARK_FORM_ID"
  write_env FORMSPARK_API_TOKEN "$FORMSPARK_API_TOKEN"
  vercel_set FORMSPARK_FORM_ID "$FORMSPARK_FORM_ID"
  trigger_set FORMSPARK_FORM_ID "$FORMSPARK_FORM_ID"
  trigger_set FORMSPARK_API_TOKEN "$FORMSPARK_API_TOKEN"

  printf '\n'
  check "Formspark accepts the token, with read and delete access to submissions" formspark_token_ok
  check "Formspark API reads the form's submissions (needs the upgraded workspace)" formspark_form_ok
  check "Vercel has FORMSPARK_FORM_ID" vercel_has FORMSPARK_FORM_ID
  check_trigger FORMSPARK_FORM_ID "$FORMSPARK_FORM_ID"
  check_trigger FORMSPARK_API_TOKEN "$FORMSPARK_API_TOKEN"
  pause "Press Enter to continue."
}

# ── (d) Trigger.dev ──────────────────────────────────────────────────────

trigger_variables_key_ok() {
  http_call "$TRIGGER_VARIABLES_KEY" GET "$TRIGGER_API/projects/$TRIGGER_PROJECT_REF/envvars/prod"
  [[ "$HTTP_STATUS" == 200 ]]
}

# Trigger.dev answers 401 only for a key it does not know. This check starts
# no run.
trigger_website_key_ok() {
  http_call "$TRIGGER_SECRET_KEY" GET "$TRIGGER_API/projects/$TRIGGER_PROJECT_REF/envvars/prod"
  [[ "$HTTP_STATUS" != 0 && "$HTTP_STATUS" != 401 ]]
}

section_d() {
  stage "(d) Trigger.dev project and keys · unblocks #51, #52 and #53"
  say "Trigger.dev runs the jobs that store requests in Neon and keep the data clean."
  open_url "https://cloud.trigger.dev"
  step "Create a project named 'setebaid-website', or open it."
  step "Open Project settings and copy the project ref (it starts with proj_)."
  ask_value TRIGGER_PROJECT_REF "Paste the project ref:"
  step "Switch to the Production environment and open API keys."
  note "The free plan gives full access keys only. That is enough for both keys."
  step "New API key: name 'website', no expiry."
  ask_value TRIGGER_SECRET_KEY "Paste the 'website' key:" secret
  step "New API key: name 'setup-script', no expiry."
  note "This key stays on this computer. The wizard uses it to write Trigger.dev variables."
  ask_value TRIGGER_VARIABLES_KEY "Paste the 'setup-script' key:" secret
  write_env TRIGGER_PROJECT_REF "$TRIGGER_PROJECT_REF"
  write_env TRIGGER_SECRET_KEY "$TRIGGER_SECRET_KEY"
  write_env TRIGGER_VARIABLES_KEY "$TRIGGER_VARIABLES_KEY"
  vercel_set TRIGGER_SECRET_KEY "$TRIGGER_SECRET_KEY"

  local name value copied=()
  for name in "${TRIGGER_VARIABLES[@]}"; do
    value=$(saved "$name")
    if [[ -n "$value" ]]; then trigger_set "$name" "$value"; copied+=("$name"); fi
  done

  printf '\n'
  check "Trigger.dev accepts the 'setup-script' key" trigger_variables_key_ok
  check "Trigger.dev knows the 'website' key" trigger_website_key_ok
  check "Vercel has TRIGGER_SECRET_KEY" vercel_has TRIGGER_SECRET_KEY
  for name in "${copied[@]}"; do check_trigger "$name" "$(saved "$name")"; done

  printf '\n'
  say "The free plan allows one alert destination. Use it for failed runs."
  step "In the project, open Alerts and click New alert. Skip this if it exists."
  step "Email: your own address. Alert me when: Task run failure. Environment: Production."
  note "The nightly gap-filler also emails you each request that reached only one path (#52, section h)."
  pause "Press Enter when the alert is saved."
}

# ── (e) Neon ─────────────────────────────────────────────────────────────

# neon_ok connects with psql and runs "select 1". The connection string goes
# to psql as PG* variables, so the password is never a command argument.
neon_ok() {
  DATABASE_URL="$DATABASE_URL" node --input-type=module -e '
    import { spawnSync } from "node:child_process";
    let url;
    try { url = new URL(process.env.DATABASE_URL); } catch {
      console.error("  This is not a valid connection string.");
      process.exit(1);
    }
    const env = { ...process.env,
      PGHOST: url.hostname, PGPORT: url.port || "5432",
      PGUSER: decodeURIComponent(url.username), PGPASSWORD: decodeURIComponent(url.password),
      PGDATABASE: decodeURIComponent(url.pathname.slice(1)),
      PGSSLMODE: url.searchParams.get("sslmode") ?? "require" };
    const channelBinding = url.searchParams.get("channel_binding");
    if (channelBinding) env.PGCHANNELBINDING = channelBinding;
    delete env.DATABASE_URL;
    const result = spawnSync("psql", ["-XtAc", "select 1"], { env, encoding: "utf8" });
    if (result.status !== 0) process.stderr.write(result.stderr);
    process.exit(result.status === 0 && result.stdout.trim() === "1" ? 0 : 1);
  '
}

section_e() {
  stage "(e) Neon database · unblocks #51 and #54"
  say "Neon is the main store for requests and for the dashboard numbers."
  if ! require psql; then
    fail "Install the PostgreSQL client (psql), then re-run section e."
    pause "Press Enter to continue."
    return 0
  fi
  open_url "https://console.neon.tech"
  step "Create a project named 'setebaid-website' on the Free plan. Region: AWS US East 1 (N. Virginia), near the Website."
  step "On the project dashboard, click Connect. Turn on Connection pooling, then copy the connection string."
  ask_value DATABASE_URL "Paste the connection string:" secret
  write_env DATABASE_URL "$DATABASE_URL"
  vercel_set DATABASE_URL "$DATABASE_URL"
  trigger_set DATABASE_URL "$DATABASE_URL"

  printf '\n'
  check "Neon accepts the connection string" neon_ok
  check "Vercel has DATABASE_URL" vercel_has DATABASE_URL
  check_trigger DATABASE_URL "$DATABASE_URL"
  pause "Press Enter to continue."
}

# ── (f) Vercel API token for analytics ───────────────────────────────────

vercel_token_ok() {
  http_call "$VERCEL_ANALYTICS_TOKEN" GET \
    "https://api.vercel.com/v9/projects/$VERCEL_PROJECT_ID?teamId=$VERCEL_TEAM_ID"
  [[ "$HTTP_STATUS" == 200 ]]
}

section_f() {
  stage "(f) Vercel API token for analytics · unblocks #53"
  say "The nightly job and the dashboard's Update button use this token to copy the visit counts into Neon."
  open_url "https://vercel.com/account/settings/tokens"
  step "Create a token named 'setebaid-analytics-copy'. Scope: Studio ROVST."
  step "Expiration: No Expiration, or the longest one offered."
  ask_value VERCEL_ANALYTICS_TOKEN "Paste the token:" secret
  write_env VERCEL_ANALYTICS_TOKEN "$VERCEL_ANALYTICS_TOKEN"

  local project_json
  if ! project_json=$(vercel_api "/v9/projects/$VERCEL_PROJECT"); then
    fail "Could not read the Vercel project IDs. Run 'vercel login', then re-run section f."
    pause "Press Enter to continue."
    return 0
  fi
  VERCEL_PROJECT_ID=$(jq -r '.id' <<<"$project_json")
  VERCEL_TEAM_ID=$(jq -r '.accountId' <<<"$project_json")
  write_env VERCEL_PROJECT_ID "$VERCEL_PROJECT_ID"
  write_env VERCEL_TEAM_ID "$VERCEL_TEAM_ID"
  trigger_set VERCEL_ANALYTICS_TOKEN "$VERCEL_ANALYTICS_TOKEN"
  trigger_set VERCEL_PROJECT_ID "$VERCEL_PROJECT_ID"
  trigger_set VERCEL_TEAM_ID "$VERCEL_TEAM_ID"
  # The Website gets VERCEL_PROJECT_ID from Vercel itself (a system variable).
  vercel_set VERCEL_ANALYTICS_TOKEN "$VERCEL_ANALYTICS_TOKEN"
  vercel_set VERCEL_TEAM_ID "$VERCEL_TEAM_ID"

  printf '\n'
  check "Vercel accepts the token for the Website project" vercel_token_ok
  check "Vercel has VERCEL_ANALYTICS_TOKEN" vercel_has VERCEL_ANALYTICS_TOKEN
  check "Vercel has VERCEL_TEAM_ID" vercel_has VERCEL_TEAM_ID
  check_trigger VERCEL_ANALYTICS_TOKEN "$VERCEL_ANALYTICS_TOKEN"
  check_trigger VERCEL_PROJECT_ID "$VERCEL_PROJECT_ID"
  check_trigger VERCEL_TEAM_ID "$VERCEL_TEAM_ID"
  pause "Press Enter to continue."
}

# ── (g) Encryption key for form entries ──────────────────────────────────

encryption_key_ok() {
  [[ "$(printf '%s' "$FORM_ENCRYPTION_KEY" | openssl base64 -d -A | wc -c)" -eq 32 ]]
}

section_g() {
  stage "(g) Encryption key for form entries · unblocks #51"
  say "The Website encrypts each request before it goes to Trigger.dev."
  say "Only the Website and the store task hold this key."
  if ! require openssl; then
    fail "Install openssl, then re-run section g."
    pause "Press Enter to continue."
    return 0
  fi
  FORM_ENCRYPTION_KEY=$(saved FORM_ENCRYPTION_KEY)
  if [[ -n "$FORM_ENCRYPTION_KEY" ]]; then
    warn "A key is already saved. A new key makes requests that still wait for a retry unreadable."
    if confirm "Replace the saved key?"; then FORM_ENCRYPTION_KEY=""; else ok "keeping the saved key"; fi
  fi
  if [[ -z "$FORM_ENCRYPTION_KEY" ]]; then
    FORM_ENCRYPTION_KEY=$(openssl rand -base64 32)
    write_env FORM_ENCRYPTION_KEY "$FORM_ENCRYPTION_KEY"
    ok "generated a new 256-bit key on this computer"
  fi
  vercel_set FORM_ENCRYPTION_KEY "$FORM_ENCRYPTION_KEY"
  trigger_set FORM_ENCRYPTION_KEY "$FORM_ENCRYPTION_KEY"

  printf '\n'
  check "The key is 32 random bytes" encryption_key_ok
  check "Vercel has FORM_ENCRYPTION_KEY" vercel_has FORM_ENCRYPTION_KEY
  check_trigger FORM_ENCRYPTION_KEY "$FORM_ENCRYPTION_KEY"
  pause "Press Enter to continue."
}

# ── (h) Resend for the gap report ────────────────────────────────────────

# Sends one real email: Resend has no check for a key with sending access only.
resend_ok() {
  local body
  body=$(jq -nc --arg to "$REPORT_EMAIL_TO" '{
    from: "Setebaid jobs <onboarding@resend.dev>", to: [$to],
    subject: "Setebaid: test of the gap report",
    text: "The nightly gap-filler can email you. No action is needed."}')
  http_call "$RESEND_API_KEY" POST "https://api.resend.com/emails" "$body"
  [[ "$HTTP_STATUS" == 200 ]]
}

section_h() {
  stage "(h) Resend for the gap report · unblocks #52"
  say "The nightly gap-filler emails you each request that reached only one path."
  say "It sends from Resend's test address, which delivers only to your Resend account's email."
  open_url "https://resend.com/api-keys"
  step "Sign in to Resend. Create an API key named 'setebaid-jobs' with Sending access."
  ask_value RESEND_API_KEY "Paste the API key:" secret
  ask_value REPORT_EMAIL_TO "The email address of your Resend account:"
  write_env RESEND_API_KEY "$RESEND_API_KEY"
  write_env REPORT_EMAIL_TO "$REPORT_EMAIL_TO"
  trigger_set RESEND_API_KEY "$RESEND_API_KEY"
  trigger_set REPORT_EMAIL_TO "$REPORT_EMAIL_TO"

  printf '\n'
  check "Resend sends a test email to $REPORT_EMAIL_TO" resend_ok
  check_trigger RESEND_API_KEY "$RESEND_API_KEY"
  check_trigger REPORT_EMAIL_TO "$REPORT_EMAIL_TO"
  note "Your Gmail filter archives Resend mail; look in All Mail for the test email."
  pause "Press Enter to continue."
}

# ── Choose the sections, check the tools, run ────────────────────────────

SECTION_IDS=(a b c d e f g h)
declare -A SECTION_TITLE=(
  [a]="Vercel Web Analytics and Plus           #49        Phase 1"
  [b]="Deploy hook and Sanity webhook          #48        Phase 1"
  [c]="Formspark form and API token            #50 #52    Phase 2"
  [d]="Trigger.dev project and keys            #51-#53    Phase 2"
  [e]="Neon database                           #51 #54    Phase 2"
  [f]="Vercel API token for analytics          #53        Phase 2"
  [g]="Encryption key for form entries         #51        Phase 2"
  [h]="Resend key for the gap report           #52        Phase 2"
)

requested=("$@")
if (( ${#requested[@]} == 0 )); then
  printf '\n%s  Setebaid QR mechanism: accounts and keys%s\n\n' "$BOLD" "$RESET"
  for id in "${SECTION_IDS[@]}"; do printf '  %s)  %s\n' "$id" "${SECTION_TITLE[$id]}"; done
  printf '\n'
  note "Run a and b first (Phase 1). Running d before c, e, f, g and h saves a copy step."
  printf '  %sWhich sections? (for example: a b, or all)%s ' "$BOLD" "$RESET"
  read -r reply || true
  reply="${reply//,/ }"
  read -ra requested <<<"${reply,,}"
fi
[[ "${requested[*]:-}" == "all" ]] && requested=("${SECTION_IDS[@]}")

SELECTED=()
for id in "${requested[@]}"; do
  [[ -n "${SECTION_TITLE[$id]:-}" ]] || { printf 'Unknown section: %s (use a to h, or all)\n' "$id" >&2; exit 1; }
done
for id in "${SECTION_IDS[@]}"; do
  for want in "${requested[@]}"; do
    if [[ "$want" == "$id" ]]; then SELECTED+=("$id"); break; fi
  done
done
(( ${#SELECTED[@]} )) || { echo "No section chosen." >&2; exit 1; }

if ! require node jq vercel; then
  echo "Install the missing tools, then run this again." >&2
  exit 1
fi
if ! vercel_api "/v9/projects/$VERCEL_PROJECT" >/dev/null 2>&1; then
  echo "The Vercel CLI cannot see $VERCEL_TEAM/$VERCEL_PROJECT. Run 'vercel login', then run this again." >&2
  exit 1
fi

TOTAL_STAGES=${#SELECTED[@]}
banner "Setebaid QR mechanism: accounts and keys"
for id in "${SELECTED[@]}"; do "section_$id"; done

finish
note "Saved values: $ENV_FILE (outside git, readable only by you)."
note "New Vercel variables reach the Website with its next deployment."
printf '\n'
